<?php
/**
 * Remove or Change Displayed States and Regions
 *
 * LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE_OSL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eltrino.com so we can send you a copy immediately.
 *
 * @category   Eltrino
 * @package    Eltrino_Region
 * @subpackage Adminhtml
 * @copyright  Copyright (c) 2012 Eltrino LLC. (http://www.eltrino.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="config collapseable">
    <table class="form-list" cellspacing="0">
    <colgroup class="label"></colgroup>
    <colgroup class="value"></colgroup>
    <colgroup class="scope-label"></colgroup>
    <colgroup class=""></colgroup>
    <tbody>
        <tr id="row_general_country_default">
            <td class="label"><label><?php echo $this->__('Country'); ?></label></td>
            <td class="value"><?php echo $this->getCountriesElmHtml(); ?></td>
            <td class="scope-label"><?php echo $this->__('[GLOBAL]'); ?></td>
            <td class=""><p><?php echo $this->getRemoveButtonHtml(); ?></p></td>
        </tr>
        <tr id="row_general_common_settings_default">
            <td class="label"><label><?php echo $this->__('Common Settings'); ?></label></td>
            <td class="value" id="common-settings"><?php echo $this->getCommonSettingsElmHtml(); ?></td>
            <td class="scope-label"><?php echo $this->__('[GLOBAL]'); ?></td>
            <td class=""></td>
        </tr>
        <tr id="row_general_country_allow">
            <td class="label"><label><?php echo $this->__('Disabled Regions'); ?></label></td>
            <td class="value" id="disabled-regions"><?php echo $this->getDisabledRegionsElmHtml(); ?></td>
            <td class="scope-label"><?php echo $this->__('[GLOBAL]'); ?><p><?php echo $this->__('Items selected in this list will NOT be displayed to customers.'); ?></p></td>
            <td class=""></td>
        </tr>
    </tbody></table>
</fieldset>