<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_CheckoutByAmazon
 * @copyright  Copyright (c) 2012 creativestyle GmbH (http://www.creativestyle.de)
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="checkoutbyamazon-badge">
    <img src="<?php echo $this->getAmazonBadgeUrl(); ?>" alt="<?php echo $this->__('Checkout by Amazon'); ?>" title="<?php echo $this->__('Checkout by Amazon'); ?>" />
</div>
<div class="ssl-logos">
	<div>
		<div class="ssl-logo-txt">
			All our payment methods are
		</div>
		<div title="All of our payment methods are secured by 256-bit SSL.">
			<img src="/skin/frontend/acme/default/images/256-ssl-encryption.png">
		</div>
	</div>
	<div>
		<div class="ssl-logo-txt">
			<span id="siteseal"><script type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=zqcqJ8EORjAWq5WcrX40zaKKm6vf96CJovX3XIAhePELjjvqCv"></script></span>
		</div>
	</div>
</div>